### ISSUE TITLE
How to switch from "single-frame mode" to "sequence mode" in this project?

### ISSUE THREAD

**Issue by carrroo** [facebookresearch/OrienterNet#10]
Hello, the paper pointed out that the accuracy of the image sequence is higher, so how to switch from "single-frame mode" to "sequence mode" in this project?
:)  Thanks!

**Comment by carrroo** [comment]
I tried to replace the file name in the "test2_files.txt"  with a sequence of images, however the accuracy didn't seem to improve

**Comment by carrroo** [comment]
I tried to replace the file name in the "test2_files.txt"  with a sequence of images, however the accuracy didn't seem to improve

**Comment by carrroo** [comment]
I tried to replace the file name in the "test2_files.txt" with a sequence of images, however the accuracy didn't seem to improve

**Comment by Skydes** [comment]
From the README:
> To run the evaluation in sequential mode (by default with 10 frames):
`
python -m maploc.evaluation.mapillary [...] --sequential
`

`maploc.evaluation.kitti` has the same flag. The maximum number of frames per segment can be updated with:
```bash
python -m maploc.evaluation.mapillary [...] --sequential chunking.max_length=20
```
I have updated the README accordingly.

**Comment by carrroo** [comment]
I saw the parameter configuration in "kitti.py" just recently, appreciate your reply

**Comment by carrroo** [comment]
_File "/home/zj/OrienterNet/maploc/data/sequential.py", line 18, in chunk_sequence
    sort_array = data.get("capture_time", data.get("index", names or indices))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()_

After I add the "--sequential" flag, it still doesn't seem to work.
Is sequential mode not suitable for KITTI?

**Comment by carrroo** [comment]
Thank you very much for your reply!
I noticed that the function _plot_example_sequential_ is not implemented, will **sequential** mode support visual export in the future?

**Comment by Skydes** [comment]
Yes, this is WIP [in this notebook](https://github.com/facebookresearch/OrienterNet/blob/main/notebooks/visualize_predictions_sequences.ipynb). I'll add code to generate sequential animations when I find the time.
